### ISSUE TITLE
spark.env.spark-update-path fails on subsequent runs

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/spark-formula#2]
The "alternatives.priority" is hardcoded as 999 in SLS file meaning "env.spark-update-path" state will fail on (re)runs.  PR #1 improves the situation replacing "requires:" with "onchanges:" but state will fail next time "onchanges" is triggered.

Best solution would be exposing as pillar and not forcing alternatives by default (refer to [commit-sqlplus-alternatives](https://github.com/saltstack-formulas/sqlplus-formula/pull/11/commits/7a3d58388aa249654594a87913aaba5c11c7c3be) and [commit-sun-java-alternatives](https://github.com/saltstack-formulas/sun-java-formula/commit/0175f6802d39c0aae84bcbe4e2c5adbc8ee9aed4) for ideas).

**Comment by jackscott** [comment]
@noelmcloughlin - Thank you for pointing this out!

This is [fixed](https://github.com/jackscott/spark-formula/commit/13241159f0f44655857c20f3fe76446ab4a0ca48) upstream and will be merged in with the 0.1.0 PR.

TIL - you can use `{{ None | strftime('%s') }}` for the priority

**Comment by noelmcloughlin** [comment]
@jackscott I love your suggestion for autogenerating alternative priority  

`{{ None | strftime('%s') }}`  Will try that!  Thanks.
